# Generated by Django 4.2.1 on 2023-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='judgements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='file not exist.pdf', max_length=255, unique=True)),
                ('judgment_path', models.FileField(upload_to='judgment/')),
                ('summary_path', models.FileField(upload_to='summary/')),
                ('keywords', models.TextField()),
            ],
        ),
    ]
